#!/usr/bin/env python3
from pathlib import Path
import re, sys

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "android/app/src/main/cpp/android_port_seg_tables.c"

COURSES = [
    "mario_raceway", "choco_mountain", "bowsers_castle", "banshee_boardwalk",
    "yoshi_valley", "frappe_snowland", "koopa_troopa_beach", "royal_raceway",
    "luigi_raceway", "moo_moo_farm", "toads_turnpike", "kalimari_desert",
    "sherbet_land", "rainbow_road", "wario_stadium", "block_fort", "skyscraper",
    "double_deck", "dks_jungle_parkway", "big_donut",
]

EXTERN_RE = re.compile(r"^extern\s+[A-Za-z_0-9 ]+?\s*\*?\s*([A-Za-z_0-9]+)\[\]", re.M)

def read(path):
    return (ROOT / path).read_text()

def symbols_with_offsets(path, seg_hint):
    out = []
    for name in EXTERN_RE.findall(read(path)):
        m = re.search(r"_dl_([0-9A-Fa-f]+)$", name)
        if m:
            out.append((int(m.group(1), 16), name)); continue
        m = re.search(r"_0([0-9A-Fa-f])([0-9A-Fa-f]{6})$", name)
        if m and int(m.group(1), 16) == seg_hint:
            out.append((int(m.group(2), 16), name))
    return out

def symbols_from_yaml(path):
    out=[]; symbol=None; offset=None; in_tables=False
    for raw in read(path).splitlines():
        stripped=raw.strip()
        if not stripped or stripped.startswith("#"): continue
        indent=len(raw)-len(raw.lstrip(" "))
        if indent == 0:
            if symbol and offset is not None: out.append((offset, symbol))
            symbol=offset=None; in_tables=False; continue
        if stripped.startswith("tables:"):
            in_tables=True; continue
        if in_tables:
            m=re.match(r"([A-Za-z_0-9]+):\s*$", stripped)
            if m and indent == 4: symbol=m.group(1); offset=None
            m=re.match(r"range:\s*\[\s*(0x[0-9A-Fa-f]+)", stripped)
            if m and symbol:
                out.append((int(m.group(1),16),symbol)); symbol=offset=None
            continue
        m=re.match(r"symbol:\s*([A-Za-z_0-9]+)", stripped)
        if m: symbol=m.group(1)
        m=re.match(r"offset:\s*(0x[0-9A-Fa-f]+)", stripped)
        if m: offset=int(m.group(1),16)
    if symbol and offset is not None: out.append((offset,symbol))
    return out

def declared_symbols(path):
    return set(re.findall(r"\b([A-Za-z_][A-Za-z_0-9]*)\s*\[", read(path)))

def emit_table(lines, cname, entries, declared=None):
    entries=[(o & 0xFFFFFF,n) for o,n in entries if re.match(r"[A-Za-z_]",n)]
    if declared is not None: entries=[e for e in entries if e[1] in declared]
    entries=sorted(set(entries))
    if not entries:
        lines.append(f"static const PortSegEntry {cname}[1] = {{ {{ 0, 0, NULL }} }};")
        lines.append(f"#define {cname}_count 0"); return
    lines.append(f"static const PortSegEntry {cname}[] = {{")
    for i,(off,sym) in enumerate(entries):
        end=entries[i+1][0] if i+1<len(entries) else 0x1000000
        lines.append(f"    {{ 0x{off:06X}, 0x{end-off:06X}, (const void*) &{sym} }},")
    lines.append("};")
    lines.append(f"#define {cname}_count {len(entries)}")

lines=[
    "/* Generated by tools/android/gen_seg_tables.py. */",
    "#include <stddef.h>",
    "#include <ultra64.h>",
    "#include <macros.h>",
    "#include <common_structs.h>",
    "#include <course.h>",
    "#include <assets/common_data.h>",
    "#include <assets/ceremony_data.h>",
    "#include <assets/startup_logo.h>",
    '#include "port/port.h"',
]
for c in COURSES:
    lines.append(f'#include "courses/{c}/course_data.h"')
    lines.append(f'#include "courses/{c}/course_displaylists.inc.h"')
lines.append("")

for c in COURSES:
    emit_table(lines,f"seg6_{c}",symbols_with_offsets(f"courses/{c}/course_data.h",6))
    emit_table(lines,f"seg7_{c}",symbols_with_offsets(f"courses/{c}/course_displaylists.inc.h",7))
    lines.append("")

lines.append("const PortCourseSegTables gPortCourseSegTables[] = {")
for c in COURSES:
    lines.append(f"    {{ {{ seg6_{c}, seg6_{c}_count }}, {{ seg7_{c}, seg7_{c}_count }} }},")
lines.append("    { { NULL, 0 }, { NULL, 0 } },")
lines.append("};")
lines.append("")

for cname,yml,hdr,var in [
    ("segD_common","yamls/us/common_data.yml","assets/common_data.h","gPortCommonDataSegTable"),
    ("segB_ceremony","yamls/us/ceremony_data.yml","assets/ceremony_data.h","gPortCeremonyDataSegTable"),
    ("seg6_logo","yamls/us/startup_logo.yml","assets/startup_logo.h","gPortStartupLogoSegTable"),
]:
    emit_table(lines,cname,symbols_from_yaml(yml),declared_symbols(hdr))
    lines.append(f"const PortSegTable {var} = {{ {cname}, {cname}_count }};")
    lines.append("")

for c in COURSES:
    for s in ["dl_mio0SegmentRomStart","dl_mio0SegmentRomEnd","offsetsSegmentRomStart","offsetsSegmentRomEnd"]:
        lines.append(f"u8 _course_{c}_{s}[1];")
    for s in ["vertexSegmentRomStart","vertexSegmentRomEnd"]:
        lines.append(f"u8 _{c}_{s}[1];")
    lines.append(f"u8 d_course_{c}_packed[1];")

OUT.parent.mkdir(parents=True,exist_ok=True)
OUT.write_text("\n".join(lines)+"\n")
print(f"[android] generated {OUT}")
